name: hupu

on:
  push:
    paths:
      - "extractors/hupu/*.go"
      - ".github/workflows/stream_hupu.yml"
  pull_request:
    paths:
      - "extractors/hupu/*.go"
      - ".github/workflows/stream_hupu.yml"
  schedule:
    # run ci weekly
    - cron: "0 0 * * 0"

jobs:
  test:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        go: ["1.21"]
        os: [ubuntu-latest]
    name: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-go@v2
        with:
          go-version: ${{ matrix.go }}

      - name: Test
        run: go test -timeout 5m -race -coverpkg=./... -coverprofile=coverage.txt github.com/iawia002/lux/extractors/hupu
